# @package _group_

scene: ficus
name: ${dataset.scene}_${dataset.resolution}
sampling:
  # fov: 20.0
  # ray_start: 3.5
  # ray_end: 4.5
  # radius: 4.0
  fov: 30.0
  ray_start: 0.75
  ray_end: 1.25
  radius: 1.0
  dist: custom
  # dist: spherical_uniform
  # horizontal_stddev: 3.141592653589793
  # vertical_stddev: 0.7417649320975901
  # horizontal_mean: 1.5707963267948966
  # vertical_mean: 0.7417649320975901
white_back: true
last_back: false
cube_scale: 0.475
